name: Java CI com Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verificar o diretório atual
      run: pwd

    - name: Listar arquivos em source-code-inspection
      run: ls -la "source-code-inspection"

    - name: Build com Maven (debug)
      run: mvn -B package --file "source-code-inspection/pom.xml"

    - name: Atualizar gráfico de dependências
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - run: echo "Este repositório é ${{ github.repository }} .."
